services:
  - type: web
    name: clearpro-fullstack
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: NODE_ENV
        value: production

      - key: JWT_SECRET
        generateValue: true

      - key: UPLOAD_DIR
        value: uploads

      - key: BASE_URL
        value: https://clearpro-fullstack.onrender.com

      - key: MONGO_URI
        value: mongodb+srv://bilsheikh5_db_user:Poppkgo%401@cluster0.lo7sj9t.mongodb.net/clearpro?retryWrites=true&w=majority&appName=Cluster0
